import {Lesson} from "../../core/models/academic/lesson";
import {LessonEvent} from "../../core/models/academic/lesson-event";
import {LessonStatus} from "../../core/enums/lesson-status";

export const LESSONS: Lesson[] = [
    {
        teacher: 'Mr. John Doe',
        level: 'Intermediate',
        description: 'Learn the basics of math for business',
        students: ['5'],
        center: 'Benguela',
        title: "",
        online: false,
        startDatetime: new Date(),
        endDatetime: new Date(),
        status: LessonStatus.AVAILABLE,
        attendances: [],
        materials: [],
    },
];

export const LESSONS_EVENTS: Partial<LessonEvent>[] = [
    {
        id: "1001",
        date: '2024-12-26',
        class: 'Online 1',
        time: '8:00 AM - 10:00 PM',
        teacher: 'Jofrey Mink',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Talatona',
        title: "Pronouns",
        start: new Date().toISOString().split('T')[0] + 'T08:00:00',
        end: new Date().toISOString().split('T')[0] + 'T10:00:00',
        backgroundColor: '#0e4f26',
        borderColor: '#0e4f26',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '10:00',
        endHour: '12:00',
        extendedProps: {
            teacher: 'Jofrey Mink',
            center: 'Talatona',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: true,
            status: 'scheduled',
            time: '8:00 AM - 10:00 PM'
        }
    },
    {
        id: "1002",
        date: '2024-12-26',
        class: 'Online 1',
        time: '08:00 AM - 10:00 PM',
        teacher: 'Dorivaldo Paulo',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Nova Vida',
        title: 'Adjectives and Nouns',
        start: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString().split('T')[0] + 'T08:00:00',
        end: new Date(new Date().setDate(new Date().getDate() + 1)).toISOString().split('T')[0] + 'T10:00:00',
        backgroundColor: '#8c221c',
        borderColor: '#8c221c',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '08:00',
        endHour: '10:00',
        extendedProps: {
            teacher: 'Dorivaldo Paulo',
            center: 'Nova Vida',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: true,
            status: 'pending',
            time: '08:00 AM - 10:00 PM'
        }
    },
    {
        id: "1003",
        date: '2024-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Maria Smith',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Maculusso',
        title: 'English for Business',
        start: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString().split('T')[0] + 'T10:00:00',
        end: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString().split('T')[0] + 'T12:00:00',
        backgroundColor: '#8c221c',
        borderColor: '#8c221c',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '10:00',
        endHour: '12:00',
        extendedProps: {
            teacher: 'Maria Smith',
            center: 'Maculusso',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: true,
            status: 'scheduled',
            time: '10:00 AM - 12:00 PM'
        }
    },
    {
        id: "1004",
        date: '2022-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Jorge Adao',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Patriota',
        title: 'English for Business',
        start: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString().split('T')[0] + 'T10:00:00',
        end: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString().split('T')[0] + 'T12:00:00',
        backgroundColor: '#282960',
        borderColor: '#282960',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '10:00',
        endHour: '12:00',
        extendedProps: {
            teacher: 'Jorge Adao',
            center: 'Patriota',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: false,
            status: 'completed',
            time: '10:00 AM - 12:00 PM'
        }
    },
    {
        id: "1005",
        date: '2024-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Luis Capinda',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Talatona',
        title: 'English for Business',
        start: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString().split('T')[0] + 'T14:00:00',
        end: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString().split('T')[0] + 'T16:00:00',
        backgroundColor: '#893f0c',
        borderColor: '#893f0c',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '10:00',
        endHour: '12:00',
        extendedProps: {
            teacher: 'Luis Capinda',
            center: 'Talatona',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: true,
            status: 'scheduled',
            time: '10:00 AM - 12:00 PM'
        }
    },
    {
        id: "1006",
        date: '2022-12-25',
        class: 'Online 1',
        time: '20:00 AM - 22:00 PM',
        teacher: 'Sebastiao Alfredo',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Maculusso',
        title: 'English for Business',
        start: new Date().toISOString().split('T')[0] + 'T20:00:00',
        end: new Date().toISOString().split('T')[0] + 'T22:00:00',
        backgroundColor: '#893f0c',
        borderColor: '#893f0c',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '10:00',
        endHour: '12:00',
        extendedProps: {
            teacher: 'Sebastiao Alfredo',
            center: 'Maculusso',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: true,
            status: 'cancelled',
            time: '20:00 AM - 22:00 PM'
        }
    },
    {
        id: "1007",
        date: '2022-12-25',
        class: 'Online 1',
        time: '14:00 PM - 16:00 PM',
        teacher: 'Jose Augusto',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Nova Vida',
        title: 'English for Business',
        start: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0] + 'T14:00:00',
        end: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString().split('T')[0] + 'T16:00:00',
        backgroundColor: '#0e4f26',
        borderColor: '#0e4f26',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '10:00',
        endHour: '12:00',
        extendedProps: {
            teacher: 'Jose Augusto',
            center: 'Nova Vida',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: false,
            status: 'pending',
            time: '14:00 PM - 16:00 PM'
        }
    },
    {
        id: "1008",
        date: '2022-12-25',
        class: 'Online 1',
        time: '07:00 AM - 09:00 PM',
        teacher: 'Ana Maya',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: ['12'],
        center: 'Maculusso',
        title: 'English for Business',
        start: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString().split('T')[0] + 'T07:00:00',
        end: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString().split('T')[0] + 'T09:00:00',
        backgroundColor: '#282960',
        borderColor: '#282960',
        textColor: '#FFFFFF',
        tag: {color: '#FF0000', name: 'Beginner'},
        startHour: '10:00',
        endHour: '12:00',
        extendedProps: {
            teacher: 'Ana Maya',
            center: 'Maculusso',
            classEntity: 'Online 1',
            description: 'Learn the basics of English for business',
            isOnline: true,
            status: 'scheduled',
            time: '07:00 AM - 09:00 PM'
        }
    },
];
