import { Lesson, LessonEvent } from 'src/app/core/models/lesson';

export const LESSONS_BY_STUDENT: Lesson[] = [
    {
        date: '2024-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Dr. Mary Jane Smith',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        center: 'Patriota',
        status: 'presente',
    },
    {
        date: '2024-12-26',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Mr. John Doe',
        level: 'Intermediate',
        description: 'Learn the basics of math for business',
        center: 'Benguela',
        status: 'ausente',
    },
    {
        date: '2024-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Dr. Mary Jane Smith',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        center: 'Patriota',
        status: 'presente',
    },
    {
        date: '2024-12-26',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Mr. John Doe',
        level: 'Intermediate',
        description: 'Learn the basics of math for business',
        center: 'Benguela',
        status: 'ausente',
    },
];

export const LESSONS_EVENTS: LessonEvent[] = [
    {
        date: '2024-12-26',
        class: 'Online 1',
        time: '8:00 AM - 10:00 PM',
        teacher: 'Jofrey Mink',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Talatona',
        title: 'English for Business',
        start: '2024-12-24T08:00:00',
        end: '2024-12-24T10:00:00',
        backgroundColor: '#0e4f26',
        borderColor: '#0e4f26',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
    {
        date: '2024-12-26',
        class: 'Online 1',
        time: '12:00 AM - 14:00 PM',
        teacher: 'Dorivaldo Paulo',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Nova Vida',
        title: 'English for Business',
        start: '2024-12-27T12:00:00',
        end: '2024-12-27T14:00:00',
        backgroundColor: '#8c221c',
        borderColor: '#8c221c',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
    {
        date: '2024-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Maria Smith',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Maculusso',
        title: 'English for Business',
        start: '2024-12-26T10:00:00',
        end: '2024-12-26T12:00:00',
        backgroundColor: '#8c221c',
        borderColor: '#8c221c',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
    {
        date: '2022-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Jorge Adao',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Patriota',
        title: 'English for Business',
        start: '2024-12-24T10:00:00',
        end: '2024-12-24T12:00:00',
        backgroundColor: '#282960',
        borderColor: '#282960',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
    {
        date: '2024-12-25',
        class: 'Online 1',
        time: '10:00 AM - 12:00 PM',
        teacher: 'Luis Capinda',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Talatona',
        title: 'English for Business',
        start: '2024-12-26T10:00:00',
        end: '2024-12-26T12:00:00',
        backgroundColor: '#893f0c',
        borderColor: '#893f0c',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
    {
        date: '2022-12-25',
        class: 'Online 1',
        time: '20:00 AM - 22:00 PM',
        teacher: 'Sebastiao Alfredo',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Maculusso',
        title: 'English for Business',
        start: '2024-12-25T20:00:00',
        end: '2024-12-25T22:00:00',
        backgroundColor: '#893f0c',
        borderColor: '#893f0c',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
    {
        date: '2022-12-25',
        class: 'Online 1',
        time: '14:00 PM - 16:00 PM',
        teacher: 'Jose Augusto',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Nova Vida',
        title: 'English for Business',
        start: '2024-12-23T14:00:00',
        end: '2024-12-23T16:00:00',
        backgroundColor: '#0e4f26',
        borderColor: '#0e4f26',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
    {
        date: '2022-12-25',
        class: 'Online 1',
        time: '07:00 AM - 09:00 PM',
        teacher: 'Ana Maya',
        level: 'Beginner',
        description: 'Learn the basics of English for business',
        students: '12',
        center: 'Maculusso',
        title: 'English for Business',
        start: '2024-12-28T07:00:00',
        end: '2024-12-28T09:00:00',
        backgroundColor: '#282960',
        borderColor: '#282960',
        textColor: '#FFFFFF',
        tag: { color: '#FF0000', name: 'Beginner' },
        startHour: '10:00',
        endHour: '12:00',
    },
];
