export enum LessonStatus {
    AVAILABLE = "AVAILABLE",
    UNAVAILABLE = "UNAVAILABLE",
    BOOKED = "BOOKED",
    COMPLETED = "COMPLETED",
    CANCELLED = "CANCELLED",
    SCHEDULED = "SCHEDULED",
    OVERDUE = 'OVERDUE'
}
