export enum StudentStatus {
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    GRADUATED = 'GRADUATED',
    DROPPED_OUT = 'DROPPED_OUT',
    SUSPENDED = 'SUSPENDED',
    TRANSFERRED = 'TRANSFERRED',
    ON_LEAVE = 'ON_LEAVE',
    PROBATION = 'PROBATION'
}
